In [1]:
%load_ext autoreload
%autoreload 2

In [2]:
import pandas as pd
import numpy as np
import os
import sys
from typing import List

# sys.path.append('/Users/harendrakumar/Documents/Loan_Prediction/')

In [4]:
%pwd

'/Users/harendrakumar/Documents/Loan_Prediction/research'

In [5]:
os.chdir("../")
%pwd

'/Users/harendrakumar/Documents/Loan_Prediction'

In [6]:
from src.mlProject.utils import databalancer, data_loader
from src.mlProject.utils import feature_selectors

In [7]:
from src.mlProject.utils.utility import (
    drop_columns_having_nulls_above_threshold,
    fill_numeric_missing_values,
    fill_categorical_missing_values,
    fill_numeric_missing_values_using_interpolation,
    drop_columns_with_IDs,
    encode_cat_columns,
    standardize_data
)

In [8]:
steps = [drop_columns_with_IDs,
         drop_columns_having_nulls_above_threshold, 
         fill_numeric_missing_values, 
         fill_categorical_missing_values,
        encode_cat_columns
        ]

In [ ]:
data_dir="../../data_folder/train"

In [10]:
df = pd.read_csv("artifacts/data_ingestion/credit_train.csv")

In [11]:
df.head()

,Loan ID,Customer ID,Loan Status,Current Loan Amount,Term,Credit Score,Annual Income,Years in current job,Home Ownership,Purpose,Monthly Debt,Years of Credit History,Months since last delinquent,Number of Open Accounts,Number of Credit Problems,Current Credit Balance,Maximum Open Credit,Bankruptcies,Tax Liens
0,14dd8831-6af5-400b-83ec-68e61888a048,981165ec-3274-42f5-a3b4-d104041a9ca9,Fully Paid,445412.0,Short Term,709.0,1167493.0,8 years,Home Mortgage,Home Improvements,5214.74,17.2,NaN,6.0,1.0,228190.0,416746.0,1.0,0.0
1,4771cc26-131a-45db-b5aa-537ea4ba5342,2de017a3-2e01-49cb-a581-08169e83be29,Fully Paid,262328.0,Short Term,NaN,NaN,10+ years,Home Mortgage,Debt Consolidation,33295.98,21.1,8.0,35.0,0.0,229976.0,850784.0,0.0,0.0
2,4eed4e6a-aa2f-4c91-8651-ce984ee8fb26,5efb2b2b-bf11-4dfd-a572-3761a2694725,Fully Paid,99999999.0,Short Term,741.0,2231892.0,8 years,Own Home,Debt Consolidation,29200.53,14.9,29.0,18.0,1.0,297996.0,750090.0,0.0,0.0
3,77598f7b-32e7-4e3b-a6e5-06ba0d98fe8a,e777faab-98ae-45af-9a86-7ce5b33b1011,Fully Paid,347666.0,Long Term,721.0,806949.0,3 years,Own Home,Debt Consolidation,8741.90,12.0,NaN,9.0,0.0,256329.0,386958.0,0.0,0.0
4,d4062e70-befa-4995-8643-a0de73938182,81536ad9-5ccf-4eb8-befb-47a4d608658e,Fully Paid,176220.0,Short Term,NaN,NaN,5 years,Rent,Debt Consolidation,20639.70,6.1,NaN,15.0,0.0,253460.0,427174.0,0.0,0.0

In [12]:
df.shape

(100514, 19)

In [13]:
def apply_transformation_steps(df, steps):
    """
    Apply a series of transformation steps to a dataframe.

    Parameters:
    df (pd.DataFrame): The input dataframe to be transformed.
    steps (list): A list of transformation functions to be applied.

    Returns:
    pd.DataFrame: The transformed dataframe.
    """
    for step in steps:
        df = step(df)
    return df

# Apply the transformation steps to the dataframe
transformed_df = apply_transformation_steps(df, steps)

[2025-11-19 11:26:44,420: INFO: utility: Dropping ID columns: ['Loan ID', 'Customer ID']]
[2025-11-19 11:26:44,428: INFO: utility: ➡️ Dropping columns with more than 50.0% null values.]
[2025-11-19 11:26:44,446: INFO: utility: ✅ Dropping columns with null percentage above 50.0: ['Months since last delinquent']]
[2025-11-19 11:26:44,470: INFO: utility: ✅Filling missing values in numeric columns.]
[2025-11-19 11:26:44,478: INFO: utility: ✅ Filling missing values in categorical columns.]
[2025-11-19 11:26:44,521: INFO: utility: Mapping for column 'Loan Status': {0: 'Charged Off', 1: 'Fully Paid'}]
[2025-11-19 11:26:44,524: INFO: utility: Mapping for column 'Term': {0: 'Long Term', 1: 'Short Term'}]
[2025-11-19 11:26:44,529: INFO: utility: Mapping for column 'Years in current job': {0: '1 year', 1: '10+ years', 2: '2 years', 3: '3 years', 4: '4 years', 5: '5 years', 6: '6 years', 7: '7 years', 8: '8 years', 9: '9 years', 10: '< 1 year'}]
[2025-11-19 11:26:44,533: INFO: utility: Mapping for column 'Home Ownership': {0: 'HaveMortgage', 1: 'Home Mortgage', 2: 'Own Home', 3: 'Rent'}]
[2025-11-19 11:26:44,539: INFO: utility: Mapping for column 'Purpose': {0: 'Business Loan', 1: 'Buy House', 2: 'Buy a Car', 3: 'Debt Consolidation', 4: 'Educational Expenses', 5: 'Home Improvements', 6: 'Medical Bills', 7: 'Other', 8: 'Take a Trip', 9: 'major_purchase', 10: 'moving', 11: 'other', 12: 'renewable_energy', 13: 'small_business', 14: 'vacation', 15: 'wedding'}]

/Users/harendrakumar/Documents/Loan_Prediction/src/mlProject/utils/utility.py:45: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  data[col].fillna(mean_value, inplace=True)
/Users/harendrakumar/Documents/Loan_Prediction/src/mlProject/utils/utility.py:78: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  data[col].fillna(mode_value, inplace=True)

In [16]:
transformed_df.head(2)

,Loan Status,Current Loan Amount,Term,Credit Score,Annual Income,Years in current job,Home Ownership,Purpose,Monthly Debt,Years of Credit History,Number of Open Accounts,Number of Credit Problems,Current Credit Balance,Maximum Open Credit,Bankruptcies,Tax Liens
0,1,445412.0,1,709.000000,1.167493e+06,8,1,5,5214.74,17.2,6.0,1.0,228190.0,416746.0,1.0,0.0
1,1,262328.0,1,1076.456089,1.378277e+06,1,1,3,33295.98,21.1,35.0,0.0,229976.0,850784.0,0.0,0.0

In [21]:
X = transformed_df.drop("Loan Status", axis=1)
y = transformed_df["Loan Status"]
feature_selectors.feature_selection(X=X, y=y, threshold=0.2)

[2025-11-19 11:37:41,589: INFO: feature_selectors: ✅ Selecting important features using RandomForest feature importances.]
[2025-11-19 11:37:56,841: INFO: feature_selectors: ➡️ Selected features: ['Credit Score']]

['Credit Score']

In [18]:
feature_selectors.select_features_by_correlation(data=transformed_df, target_column="Loan Status")

[2025-11-19 11:30:52,823: INFO: feature_selectors: ➡️ Selecting features with correlation above 0.1 with target 'Loan Status'.]
[2025-11-19 11:30:52,880: INFO: feature_selectors: ✅ Selected features based on correlation: ['Current Loan Amount', 'Term', 'Credit Score']]

['Current Loan Amount', 'Term', 'Credit Score']

In [22]:
feature_selectors.select_features_using_VIF(data=transformed_df)

[2025-11-19 11:38:26,281: INFO: feature_selectors: ➡️ Selecting features using VIF with threshold = 5.0.]
[2025-11-19 11:38:26,994: INFO: feature_selectors: Removing feature 'Number of Credit Problems' with VIF = 8.38953738916768.]
[2025-11-19 11:38:27,573: INFO: feature_selectors: Removing feature 'Years of Credit History' with VIF = 6.824876711873249.]
[2025-11-19 11:38:28,064: INFO: feature_selectors: Removing feature 'Number of Open Accounts' with VIF = 6.102166724524711.]
[2025-11-19 11:38:28,467: INFO: feature_selectors: ✅ Selected features after VIF check: ['Loan Status', 'Current Loan Amount', 'Term', 'Credit Score', 'Annual Income', 'Years in current job', 'Home Ownership', 'Purpose', 'Monthly Debt', 'Current Credit Balance', 'Maximum Open Credit', 'Bankruptcies', 'Tax Liens']]

['Loan Status',
 'Current Loan Amount',
 'Term',
 'Credit Score',
 'Annual Income',
 'Years in current job',
 'Home Ownership',
 'Purpose',
 'Monthly Debt',
 'Current Credit Balance',
 'Maximum Open Credit',
 'Bankruptcies',
 'Tax Liens']

In [24]:
databalancer.DataBalancer(data=transformed_df, target_column="Loan Status").balance_data().head(2)

🤖 Auto-selected method based on imbalance ratio (0.29): UNDER
✅ Balancing done using: UNDER
New class distribution:
Counter({0: 22639, 1: 22639})

,Current Loan Amount,Term,Credit Score,Annual Income,Years in current job,Home Ownership,Purpose,Monthly Debt,Years of Credit History,Number of Open Accounts,Number of Credit Problems,Current Credit Balance,Maximum Open Credit,Bankruptcies,Tax Liens,Loan Status
5,206602.0,1,7290.000000,8.968570e+05,1,1,3,16367.74,17.3,6.0,0.0,215308.0,272448.0,0.0,0.0,0
7,648714.0,0,1076.456089,1.378277e+06,10,1,1,14806.13,8.2,15.0,0.0,193306.0,864204.0,0.0,0.0,0

In [14]:
standard_data = standardize_data(df=transformed_df, target_column="Loan Status")

[2025-11-19 11:26:52,029: INFO: utility: ✅ Standardizing data using StandardScaler, excluding target column: Loan Status]
[2025-11-19 11:26:52,046: INFO: utility: ✅ Data standardization completed successfully.]

In [15]:
standard_data.head(3)

,Current Loan Amount,Term,Credit Score,Annual Income,Years in current job,Home Ownership,Purpose,Monthly Debt,Years of Credit History,Number of Open Accounts,Number of Credit Problems,Current Credit Balance,Maximum Open Credit,Bankruptcies,Tax Liens,Loan Status
0,-0.356000,0.620394,-2.769925e-01,-2.167903e-01,1.380643,-0.978537,0.525078,-1.088932,-0.142423,-1.023690,1.722987,-0.176642,-0.041035,2.513107,-0.113542,1
1,-0.361761,0.620394,1.713968e-16,-2.394656e-16,-0.834315,-0.978537,-0.354184,1.217548,0.413505,4.764912,-0.348683,-0.171894,0.010733,-0.335382,-0.113542,1
2,2.776244,0.620394,-2.528705e-01,8.779409e-01,1.380643,0.069641,-0.354184,0.881165,-0.470279,1.371593,1.722987,0.008928,-0.001277,-0.335382,-0.113542,1

In [ ]:
df.columns[df.columns.str.contains("ID")].tolist()

In [ ]:
df.columns

In [ ]:
balanced_df = databalancer.DataBalancer(data=df, target_column='Loan Status').balance_data()

In [ ]:
balanced_df.head(5)

In [ ]:
balanced_df['Loan Status'].value_counts()